### ISSUE TITLE
error: package "webview-rs-linux-x64-gnu" 

### ISSUE THREAD

**Issue by vitalspace** [2nthony/webview-rs#1]
error: package "webview-rs-linux-x64-gnu" not found registry.npmjs.org/webview-rs-linux-x64-gnu 404

Any idea?

**Comment by 2nthony** [comment]
thanks, I will check this out later.

**Comment by 2nthony** [comment]
hi, the build has not passed my M1 device, and it seems the dep repo: https://github.com/Boscop/web-view is under unmaintaince, and I am gonna archive this repo. Recommended to try the new solution: Tauri.
